<?php
declare(strict_types=1);

$databaseDir = dirname(__DIR__) . '/database';
require $databaseDir . '/DatabaseConnectionInterface.php';
require $databaseDir . '/PdoDatabaseConnection.php';
require $databaseDir . '/DatabaseMigrationInterface.php';
require $databaseDir . '/MigrationRepository.php';
require $databaseDir . '/MigrationRunner.php';
require dirname(__DIR__) . '/accounts/MgwIdGenerator.php';
require dirname(__DIR__) . '/accounts/AccountIdentityService.php';
require dirname(__DIR__) . '/accounts/MgwProfileService.php';

if (!extension_loaded('pdo_sqlite')) throw new RuntimeException('MgwProfileIdentityCorrectiveTest requires pdo_sqlite.');

$assertions = 0;
$assertSame = static function (mixed $expected, mixed $actual, string $message) use (&$assertions): void {
    $assertions++;
    if ($expected !== $actual) throw new RuntimeException($message . ': expected ' . var_export($expected, true) . ', got ' . var_export($actual, true));
};
$assertTrue = static function (bool $condition, string $message) use (&$assertions): void {
    $assertions++;
    if (!$condition) throw new RuntimeException($message);
};
$assertThrowsExact = static function (callable $callback, string $expected, string $message) use (&$assertions): void {
    $assertions++;
    try { $callback(); }
    catch (Throwable $error) {
        if ($error->getMessage() === $expected) return;
        throw new RuntimeException($message . ': unexpected error ' . $error->getMessage());
    }
    throw new RuntimeException($message . ': no error was thrown');
};

$pdo = new PDO('sqlite::memory:');
$pdo->exec('PRAGMA foreign_keys = ON');
$database = new PdoDatabaseConnection($pdo);
$runner = new MigrationRunner($database, $databaseDir . '/migrations');
$assertSame(9, $runner->migrate(false)['executed_count'], 'Corrective profile test must use the current schema');

$accounts = new AccountIdentityService($database, 3600);
$profiles = new MgwProfileService($database);
$first = $accounts->resolveTelegramUser([
    'id' => '50001',
    'first_name' => 'Telegram Name',
    'username' => 'telegram_native',
    'photo_url' => 'https://example.test/provider-avatar.jpg',
], 'profile-session-1');
$profile = $profiles->publicProfile($first['mgw_id']);

$assertTrue(preg_match('/^Player\d{7}$/', (string)$profile['nickname']) === 1, 'Visible nickname must be generated by MGW and fit the 13-character cap');
$assertSame($profile['nickname'], $profile['display_name'], 'Compatibility display name must equal canonical nickname');
$assertSame(null, $profile['username'], 'Provider username must not be exposed as game nickname');
$assertSame('starter-default-01', $profile['avatar']['item_id'] ?? null, 'Canonical starter avatar must own visible avatar slot');
$assertSame('telegram', $profile['identities'][0]['provider'] ?? null, 'Telegram may remain visible only as a linked auth provider');
$assertSame(1, count($profile['identities']), 'Only real linked provider must be visible initially');

$originalNickname = $profile['nickname'];
$accounts->resolveTelegramUser([
    'id' => '50001',
    'first_name' => 'Provider Changed Name',
    'username' => 'provider_changed',
    'photo_url' => 'https://example.test/provider-avatar-2.jpg',
], 'profile-session-2');
$afterProviderRefresh = $profiles->publicProfile($first['mgw_id']);
$assertSame($originalNickname, $afterProviderRefresh['nickname'], 'Repeated provider auth must not overwrite MGW nickname');
$assertSame('starter-default-01', $afterProviderRefresh['avatar']['item_id'] ?? null, 'Repeated provider auth must not overwrite MGW avatar');

$database->execute(
    'INSERT INTO mgw_identities (mgw_id, provider, provider_subject, provider_username, linked_at_utc, last_authenticated_at_utc)
     VALUES (:mgw_id, :provider, :subject, NULL, :linked_at, :auth_at)',
    [
        'mgw_id' => $first['mgw_id'],
        'provider' => 'legacy_import',
        'subject' => 'legacy-50001',
        'linked_at' => '2026-08-16 00:00:00.000000',
        'auth_at' => '2026-08-16 00:00:00.000000',
    ]
);
$withLegacy = $profiles->publicProfile($first['mgw_id']);
$assertSame(1, count($withLegacy['identities']), 'Internal legacy_import identity must be hidden from Profile UI contract');
$assertSame(1, (int)$database->fetchValue("SELECT COUNT(*) FROM mgw_identities WHERE provider = 'legacy_import'"), 'Hidden legacy_import identity must remain stored for migration/recovery');

$updated = $profiles->updateProfile($first['mgw_id'], ['nickname' => 'Царь у дворца']);
$assertSame('Царь у дворца', $updated['nickname'], 'MGW nickname must support Cyrillic and spaces within the final length cap');
$assertSame('Царь у дворца', $updated['display_name'], 'Edited nickname must feed the shared visible identity projection');
$assertSame('Царь у дворца', (string)$database->fetchValue('SELECT display_name FROM mgw_users WHERE mgw_id = :mgw_id', ['mgw_id' => $first['mgw_id']]), 'Legacy display_name compatibility must follow edited MGW nickname');
$assertThrowsExact(
    static fn() => $profiles->updateProfile($first['mgw_id'], ['nickname' => '12345678901234']),
    MgwIdentityPolicy::NICKNAME_TOO_LONG_ERROR,
    'Fourteen-character nickname must be rejected by the canonical backend owner'
);

$second = $accounts->resolveTelegramUser(['id' => '50002', 'first_name' => 'Second', 'username' => 'second_provider'], 'profile-session-3');
$assertThrowsExact(
    static fn() => $profiles->updateProfile($second['mgw_id'], ['nickname' => 'Царь у дворца']),
    MgwIdentityPolicy::NICKNAME_TAKEN_ERROR,
    'Duplicate nickname must return the exact localized product error'
);

$avatar2 = $profiles->updateProfile($first['mgw_id'], ['avatar_item_id' => 'starter-default-02']);
$assertSame('starter-default-02', $avatar2['avatar']['item_id'] ?? null, 'Second starter avatar ID must be selectable');
$avatar3 = $profiles->updateProfile($first['mgw_id'], ['avatar_item_id' => 'starter-default-03']);
$assertSame('starter-default-03', $avatar3['avatar']['item_id'] ?? null, 'Third starter avatar ID must be selectable');
$locale = $profiles->updateProfile($first['mgw_id'], ['preferred_locale' => 'ru']);
$assertSame('ru', $locale['preferred_locale'], 'Explicit supported locale must persist on MGW account');

$assertions++;
try {
    $profiles->updateProfile($first['mgw_id'], ['preferred_locale' => 'en']);
    throw new RuntimeException('Unsupported EN locale must not be offered or persisted before catalog readiness');
} catch (InvalidArgumentException) {
    // Expected: RU is the only complete catalog in MVP-16.5.
}

fwrite(STDOUT, "MgwProfileIdentityCorrectiveTest: {$assertions} assertions passed\n");
