import fs from 'node:fs';

const read = path => fs.readFileSync(path, 'utf8');
const assert = (condition, message) => { if (!condition) throw new Error(message); };

const launch = read('bot/helpers/WebAppLaunchUrl.php');
const entry = read('app/v110.php');
const manifest = read('app/runtime/client/version-manifest.php');
const activeMain = read('app/assets/js/main-v110-reconnect-v174.js');
const friends = read('app/assets/js/screens/friends-screen-v110.js');
const router = read('app/assets/js/router.js');
const api = read('app/assets/js/api/client.js');
const accountShortcuts = read('app/assets/js/components/account-shortcuts.js');
const shieldVisuals = read('app/assets/js/components/shield-king-visuals.js');
const friendsCss = read('app/assets/css/friends-v110.css');
const shortcutCss = read('app/assets/css/components/account-shortcuts.css');
const inviteWrapper = read('app/assets/js/games/game-invites-v110-rematch-policy-v175.js');
const inviteOwner = read('app/assets/js/games/game-invites-v110.js');
const endpoint = read('bot/friends.php');

assert(launch.includes("private const ENTRY_PATH = '/app/v110.php?v=1127';"), 'Telegram launch owner must remain v110.php?v=1127');
assert(entry.includes("app/runtime/client/version-manifest.php") || entry.includes("runtime/client/version-manifest.php"), 'v110 entry must still render version manifest');
assert(manifest.includes("'@mgw/main' => './assets/js/main-v110-reconnect-v174.js?v=2'"), 'Accepted reconnect wrapper cache identity must remain frozen');
assert(activeMain.includes("import './production-v110-reconnect-v174.js?v=1';"), 'Active main must preserve accepted reconnect owner');
assert(activeMain.includes("import './main-v110.js?v=1139"), 'Active main must preserve accepted shell graph');
assert(!activeMain.includes('friends-screen-v110.js'), 'Friends must not modify the frozen reconnect composition owner');
assert(accountShortcuts.includes("import('../screens/friends-screen-v110.js?v=5&mvp18=instant-route&optimistic-relations')"), 'Existing account shortcut owner must lazy-load the instant Friends module on demand');
assert(accountShortcuts.includes('closeSheet();') && accountShortcuts.indexOf('closeSheet();') < accountShortcuts.indexOf('await loadFriendsModule()'), 'Friends shortcut must close the menu synchronously before awaiting its module');
assert(accountShortcuts.includes('void loadFriendsModule();'), 'Friends module must prewarm while the menu is visible');
assert(manifest.includes("game-invites-v110-rematch-policy-v175.js?v=1&fp=2"), 'Accepted rematch wrapper cache identity must remain frozen');
assert(inviteWrapper.includes("v=1142&zone=unified&rematch=optimistic&terminal=self-silent"), 'Accepted rematch wrapper must keep its frozen base invite specifier');
assert(manifest.includes("'./assets/js/games/game-invites-v110.js?v=1142&zone=unified&rematch=optimistic&terminal=self-silent' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe'"), 'Frozen wrapper specifier must converge through the manifest on the current draft-safe Telegram-share owner');
assert(manifest.includes("'./assets/js/games/game-invites-v110.js?v=1143&zone=unified&rematch=optimistic&terminal=self-silent&social=1' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe'"), 'Existing Friends invite specifier must converge on the same current invite owner');
assert(manifest.includes("'./assets/js/games/game-invites-v110.js?v=1144&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe'"), 'Previously resolved Telegram-share owner must cache-bust to the draft-safe waiting owner');
assert(friends.includes("game-invites-v110.js?v=1143&zone=unified&rematch=optimistic&terminal=self-silent&social=1"), 'Friends must keep handing off through its accepted invite specifier');
assert(inviteOwner.includes('export function openSocialPlayerInvite'), 'Existing invite owner must expose one bounded social entry');
assert(inviteOwner.includes("inviteRequest('create_direct'"), 'Social invite must remain inside existing direct-invite lifecycle owner');
assert(!friends.includes('/bot/invites.php'), 'Friends UI must not create a second invite endpoint owner');
assert(friends.includes('openSocialPlayerInvite'), 'Friends Invite action must hand off to existing invite owner');
assert(router.includes("friends:Object.freeze({ screen:'friends', shell:false })"), 'Friends must be a registered sub-route');
assert(api.includes("const FRIENDS_URL = `${window.location.origin}/bot/friends.php`;"), 'Active API client must use canonical Friends endpoint');
assert(api.includes('friends: (payload = {}) => requestUrl(FRIENDS_URL, payload)'), 'Active API client must expose Friends request helper');
assert(accountShortcuts.includes("trigger.id === 'moreMenuOpen'"), 'Friends shortcut must be limited to normal topbar menu');
assert(!accountShortcuts.includes("trigger.id === 'gameMenuOpen' ? true"), 'Game menu must not bypass active-match navigation lock');
assert(accountShortcuts.includes('account-menu-entry--friends') && accountShortcuts.includes('account-menu-entry--orders'), 'Friends and Store orders must have explicit menu presentation roles');
assert(shieldVisuals.includes("setIconOnly(icon, 'ui/navigation/friends.webp')"), 'Friends menu must use the accepted full-size navigation artwork');
assert(shortcutCss.includes('.account-menu-entry--friends .account-menu-copy strong') && shortcutCss.includes('font-size:16px'), 'Friends menu title must stay large and white');
assert(friendsCss.includes('linear-gradient(145deg,#1c1d28,#12151e)') && !friendsCss.includes('background:rgba(255,255,255,.86)'), 'Friend cards must use the dark MGW surface, never the old white card');
assert(friends.includes("tabButton('friends', 'Друзья'") && friends.includes("tabButton('requests', 'Заявки'") && friends.includes("tabButton('recent', 'Недавние'") && friends.includes("tabButton('blocked', 'Блокировки'"), 'Friends data groups must use compact explicit tabs');
assert(friends.includes("response?.result?.players") && friends.includes('searchResults.map'), 'Partial lookup must render a bounded explicit result list');
assert(endpoint.includes("'players' => $service->searchPlayers") && endpoint.includes("'limit' => FriendGraphService::SEARCH_LIMIT"), 'Friends endpoint must expose bounded canonical partial nickname search');
assert(!friends.includes('Минимум 2 символа ника или полный MGW-ID.'), 'Search must not repeat the self-evident minimum-length hint below the input');
assert(friendsCss.includes('.friends-v110-profile{') && friendsCss.includes('overflow-y:auto'), 'Public profile must scroll through all game statistics inside the bounded sheet');
assert(friendsCss.includes('.friends-v110-report .form-input') && friendsCss.includes('appearance:none'), 'Report controls must use the dark MGW field system instead of browser-grey rectangles');
assert(!friends.includes('<select') && friends.includes('data-report-reason-menu'), 'Report reason must use the managed MGW dropdown instead of the native browser select');
assert(friendsCss.includes('.friends-v110-report-select-menu') && friendsCss.includes('button[aria-selected="true"]'), 'Managed report options must preserve the dark selected state');
assert(friends.includes('const FRIENDS_REFRESH_MS = 5000') && friends.includes("currentScreen() === 'friends'"), 'Friends snapshot must refresh while the route stays visible');
assert(friends.includes('applyOptimisticRelation(action, targetMgwId)') && friends.includes('refreshSnapshot({ silent:true })'), 'Friend mutations must update locally and reconcile without a full loading repaint');
assert(!friends.includes('await refreshSnapshot();'), 'Friend mutations must never replace the page with the blocking loading state');
assert(friendsCss.includes('#screen-friends{') && friendsCss.includes('transition:none'), 'Friends route must cover the previous screen without a visible cross-fade underlayer');
assert(friends.includes("new CustomEvent('mgw:notifications-refresh')"), 'Changed social snapshots must immediately refresh the existing bell owner');
assert(friends.includes("section('Входящие заявки'"), 'Friends UI must render incoming requests');
assert(friends.includes("section('Исходящие заявки'"), 'Friends UI must render outgoing requests');
assert(friends.includes("section('Друзья'"), 'Friends UI must render friends');
assert(friends.includes("section('Недавние соперники'"), 'Friends UI must render recent opponents');
assert(friends.includes("section('Заблокированные'"), 'Friends settings must render the canonical blocked list');
for (const action of ['invite','profile','remove','report','block']) {
  assert(friends.includes(`data-social-menu-action=\\\"${action}\\\"`) || friends.includes(`data-social-menu-action="${action}"`), `Player context menu must include ${action}`);
}
assert(friends.includes("action:'report'"), '18.5 report action must use the structured Friends moderation endpoint');
assert(!friends.includes("api.support('player_report'"), 'Legacy free-text support must no longer own player reports');
assert(friends.includes("mutation === 'unblock'"), 'Blocked list must require explicit unblock handling');
assert(friends.includes("openConfirmSheet("), 'Unblock must stay behind a confirmation sheet');
assert(!friends.toLowerCase().includes('phone') && !friends.toLowerCase().includes('email') && !friends.toLowerCase().includes('real name'), 'Friends UI must not introduce prohibited identity search fields');
assert(endpoint.includes("'player_profile'"), 'Friends endpoint must expose read-only public player profile projection');
assert(endpoint.includes('SocialPlayerProfileReader'), 'Player profile action must use dedicated read-only projection');
assert(endpoint.includes("'report' => $reports->submit("), 'Friends endpoint must hand reports to the canonical DB queue service');
assert(endpoint.includes('SocialFriendNotificationService'), 'Friend request and acceptance events must enter the canonical bell pipeline');
assert(endpoint.includes("['request', 'accept', 'decline', 'cancel', 'block']"), 'Every relation resolution must reconcile stale friend-request notifications');

console.log('PASS: MVP-18.2/18.5 active Friends UI contract');
