import fs from 'node:fs';
const read = path => fs.readFileSync(path, 'utf8');
const assert = (condition, message) => { if (!condition) throw new Error(message); };
const renderer = read('app/assets/js/games/battleship/renderer.js');
const wrapper = read('app/assets/js/games/battleship/renderer-cosmetics-v1.js');
const manifest = read('app/runtime/client/version-manifest.php');
const ru = JSON.parse(read('app/locales/ru.json'));
const baseline = JSON.parse(read('ops/checks/mvp27_1_hardcoded_text_baseline.json'));
assert(!/[\u0400-\u04FF]/.test(renderer), 'Active Battleship base renderer must contain zero hardcoded Cyrillic.');
assert(renderer.includes("from '@mgw/i18n'") && renderer.includes("const battleshipText ="), 'Battleship renderer must use canonical @mgw/i18n.');
assert(renderer.includes("battleshipText('status.your_shot')") && renderer.includes("battleshipText('status.opponent_turn')"), 'Turn status copy must resolve through locale keys.');
assert(renderer.includes("battleshipText('errors.touching')") && renderer.includes("battleshipText('errors.straight_continuous')"), 'Placement validation presentation must resolve through locale keys.');
assert(renderer.includes("battleshipText('shot.self_miss')") && renderer.includes("battleshipText('shot.opponent_sunk')"), 'Authoritative shot feedback copy must resolve through locale keys.');
assert(renderer.includes("const delay = result === 'miss' ? 900 : 1250;"), 'Accepted 900/1250ms field handoff timing must remain unchanged.');
assert(renderer.includes("onAction?.({ type:'fire', cell:Number(button.dataset.battleshipCell) });"), 'Fire action ownership must remain unchanged.');
assert(renderer.includes("onAction?.({") && renderer.includes("type:'place_ship'") && renderer.includes("type:'randomize_fleet'") && renderer.includes("type:'clear_fleet'"), 'Setup action ownership must remain unchanged.');
assert(wrapper.includes("from './renderer.js?v=61&shot=miss-no-impact&base=mvp19_12-live-maps-fleets-v4&mvp27_1=localized-v1'"), 'LIVE cosmetics wrapper must point to localized base renderer identity.');
assert(manifest.includes('renderer-cosmetics-v1.js?v=6') && manifest.includes('mvp27_1=battleship-localized-v1'), 'Canonical manifest must publish localized Battleship wrapper identity.');
assert(ru._meta?.version === 35, 'RU locale revision must publish Battleship localization v35.');
assert(ru.games?.battleship?.ui?.setup?.title === 'Расставьте флот', 'Accepted RU setup title must remain unchanged.');
assert(ru.games?.battleship?.ui?.shot?.self_hit === 'Попадание! Стреляйте ещё', 'Accepted RU hit feedback must remain unchanged.');
assert(ru.games?.battleship?.ui?.errors?.touching === 'Здесь нельзя: корабли не должны соприкасаться даже по диагонали.', 'Accepted RU placement guard copy must remain unchanged.');
assert(ru.games?.battleship?.ui?.aria?.cell === 'Клетка {coord}: {state}', 'Accepted RU accessibility copy must remain unchanged.');
assert(baseline.cyrillic_lines_total === 3570 && baseline.by_scope?.client === 1889, 'Battleship localization debt baseline must ratchet by exactly 49 client lines.');
console.log('MVP27_1_BATTLESHIP_LOCALIZATION_CONTRACT=PASS');
console.log('MVP27_1_ACTIVE_BATTLESHIP_HARDCODED_CYRILLIC=0');
