<?php
declare(strict_types=1);

ob_start();
require __DIR__ . '/landing-v9.php';
$html = (string) ob_get_clean();

$replacements = [
    'Mini Games World — игровая платформа внутри Telegram: быстрые матчи 1 на 1, Match-комната, будущая Gold-комната, приглашения друзей и новые мини-игры.' => 'Mini Games World — игровая платформа внутри Telegram: быстрые матчи 1 на 1, комнаты Match и Gold, история игр и новые мини-игры.',
    'Мини-игры, быстрые матчи и приглашения друзей прямо внутри Telegram.' => 'Мини-игры и быстрые матчи прямо внутри Telegram.',
    'Mini-games, quick matches and friend invitations directly inside Telegram.' => 'Mini-games and quick matches directly inside Telegram.',
    'Mini Games World — платформа для быстрых матчей один на один. Две комнаты, приглашения друзей, история игр и новые режимы в одном Telegram Mini App.' => 'Mini Games World — платформа для быстрых матчей один на один. Две комнаты, история игр и новые режимы в одном Telegram Mini App.',
    'Mini Games World is a platform for quick 1v1 matches with two rooms, friend invites, match history and new modes inside one Telegram Mini App.' => 'Mini Games World is a platform for quick 1v1 matches with two rooms, match history and new modes inside one Telegram Mini App.',
    'Играйте в быстрые матчи, приглашайте друзей и собирайте победы.' => 'Играйте в быстрые матчи, находите соперников и сохраняйте результаты.',
    'Play quick matches, invite friends and collect wins.' => 'Play quick matches, find opponents and keep a record of your results.',
    'Фиксированная ставка. Найдите соперника или пригласите друга.' => 'Фиксированная ставка. Найдите игрока или сыграйте с игровым ботом.',
    'Fixed stake. Find an opponent or invite a friend.' => 'Fixed stake. Find a player or play against a game bot.',
    'Игра с друзьями' => 'Матч с ботом',
    'Play with friends' => 'Bot match',
    'Приглашения в Telegram' => 'Если игрок не найден',
    'Telegram invites' => 'When no player is found',
    'Первая доступная игра Mini Games World. Выбирайте классическое поле 3×3 или более глубокие форматы 6×6 и 9×9, находите случайного соперника либо приглашайте друга. Быстрые ходы, понятные правила и отдельная история каждого матча.' => 'Первая доступная игра Mini Games World. Выбирайте поля 3×3, 5×5 или 9×9 и запускайте поиск соперника. В Match-комнате при долгом ожидании может подключиться игровой бот. Результат каждого завершённого матча сохраняется в истории.',
    'The first playable Mini Games World title. Choose the classic 3×3 board or deeper 6×6 and 9×9 formats, find a random opponent or invite a friend. Quick turns, familiar rules and a separate record for every match.' => 'The first playable Mini Games World title. Choose a 3×3, 5×5 or 9×9 board and start matchmaking. In the Match room, a game bot may join after a wait. Every completed result is saved in match history.',
    'случайный игрок или друг' => 'игрок или игровой бот',
    'random player or friend' => 'player or game bot',
    'Игра открывается внутри привычного приложения и использует ваш Telegram-профиль для входа, приглашений и уведомлений.' => 'Игра открывается внутри Telegram и использует подтверждённые данные профиля для входа. Игровые приглашения и пользовательские уведомления пока не запущены.',
    'The game opens inside a familiar app and uses your Telegram profile for access, invitations and notifications.' => 'The game opens inside Telegram and uses verified profile data for access. Player invitations and user notifications are not available yet.',
    'Друзья уже рядом' => 'Поиск без ожидания',
    'Friends are already there' => 'Faster matchmaking',
    'Приглашение в матч отправляется прямо в Telegram.' => 'В Match-комнате после ожидания может подключиться игровой бот.',
    'Match invitations are sent directly in Telegram.' => 'A game bot may join in the Match room after a wait.',
    '24/7' => 'Telegram',
    'доступность сервиса' => 'точка входа в игру',
    'service availability' => 'entry point to the game',
    '✓Еженедельные начисления активным игрокам' => '✓Еженедельные начисления готовятся к запуску',
    'Weekly rewards for active players' => 'Weekly rewards are being prepared',
    'Готовится' => 'Тестовый режим',
    'Preparing' => 'Test mode',
    '✓Пополнения и вывод средств' => '✓Заявки на пополнение и магазин призов',
    'Funding and withdrawals' => 'Top-up requests and prize shop',
    'Соревновательный режим откроется после финального тестирования.' => 'Комната доступна в тестовом режиме; в Gold-поиске участвуют только живые игроки.',
    'The competitive mode will open after final testing.' => 'The room is available in test mode; Gold matchmaking connects human players only.',
    'Бот станет вашей точкой входа в игру и будет присылать приглашения и важные уведомления.' => 'Бот станет точкой входа: через него можно открыть Mini App. Игровые приглашения и уведомления появятся позже.',
    'The bot is your entry point and delivers invitations and important updates.' => 'The bot is the entry point used to open the Mini App. Player invitations and notifications will be added later.',
    'Запустите быстрый поиск случайного игрока или создайте приглашение для друга. После завершения результат и изменения баланса сохранятся в истории.' => 'Запустите поиск игрока с теми же условиями. В Match-комнате после ожидания может подключиться бот. Результат и изменения баланса сохранятся в истории.',
    'Start quick matchmaking or create an invitation for a friend. The result and balance changes are saved in your history.' => 'Start matchmaking with the same conditions. In the Match room, a bot may join after a wait. Results and balance changes are saved in history.',
    'Случайный соперник или друг' => 'Игрок или бот в Match',
    'Random opponent or friend' => 'Player or Match bot',
    '58%' => 'MVP',
    'Крестики-нолики, поиск случайного соперника, приглашения друзей, статистика и история матчей.' => 'Крестики-нолики, поиск соперника, матчи с игровым ботом в Match-комнате, статистика и история матчей.',
    'Tic-tac-toe, random matchmaking, friend invites, statistics and match history.' => 'Tic-tac-toe, matchmaking, bot games in the Match room, statistics and match history.',
    'Дорабатываем выбор ставки, пополнения, финансовую историю, вывод и защиту операций.' => 'Gold доступна в тестовом режиме: работают выбор ставки, отдельный баланс, заявки на пополнение, история операций и магазин призов.',
    'Finalizing stake selection, deposits, financial history, withdrawals and transaction protection.' => 'Gold is available in test mode with selectable stakes, a separate balance, top-up requests, transaction history and a prize shop.',
    'Пополнения</span><span class="i18n" data-lang="en">Deposits' => 'Заявки на пополнение</span><span class="i18n" data-lang="en">Top-up requests',
    'Вывод средств' => 'Магазин призов',
    'Withdrawals' => 'Prize shop',
    'Собрали понятные ответы о запуске Mini App, игровых комнатах, коинах, матчах с друзьями, безопасности и будущих обновлениях.' => 'Собрали понятные ответы о запуске Mini App, игровых комнатах, коинах, поиске соперника, безопасности и будущих обновлениях.',
    'Clear answers about launching the Mini App, game rooms, coins, friend matches, safety and upcoming updates.' => 'Clear answers about launching the Mini App, game rooms, coins, matchmaking, safety and upcoming updates.',
    'Игра с друзьями</span><span class="i18n" data-lang="en">Friends' => 'Приглашения</span><span class="i18n" data-lang="en">Invites',
    'Профиль, балансы, история матчей и приглашения друзей находятся внутри одного Mini App.' => 'Профиль, отдельные балансы, история операций и история матчей находятся внутри одного Mini App.',
    'Your profile, balances, match history and friend invitations all stay inside one Mini App.' => 'Your profile, separate balances, transaction history and match history all stay inside one Mini App.',
    'Можно искать случайного соперника или пригласить друга. Результат матча и изменения баланса сохраняются в истории.' => 'Можно искать игрока с такими же условиями. Если в Match-комнате живой соперник не найден, после ожидания может подключиться игровой бот. Результат и изменения баланса сохраняются в истории.',
    'You can find a random opponent or invite a friend. Match results and balance changes are saved in history.' => 'You can search for a player with the same conditions. If no human opponent is found in the Match room, a game bot may join after a wait. Results and balance changes are saved in history.',
    'Gold — отдельный соревновательный режим с собственным балансом и выбором размера ставки. В нём планируются пополнение, история финансовых операций и вывод средств.' => 'Gold — отдельная комната с собственным балансом и выбором стоимости участия. Сейчас доступны заявки на пополнение, история операций и магазин сертификатов за Gold-коины.',
    'Gold is a separate competitive mode with its own balance and selectable stakes. Funding, financial history and withdrawals are planned.' => 'Gold is a separate room with its own balance and selectable entry cost. Top-up requests, transaction history and a certificate prize shop are available.',
    'Комната пока готовится к запуску. Перед открытием проверяются расчёты, защита от повторных списаний и корректное завершение матчей при нестабильном соединении.' => 'Комната доступна в тестовом режиме. В Gold подбираются только живые игроки с одинаковой ставкой и размером поля.',
    'The room is still being prepared. Calculations, duplicate-charge protection and reliable match completion under unstable connections are being tested before launch.' => 'The room is available in test mode. Gold matchmaking connects human players who selected the same stake and board size.',
    'Каждый понедельник в 12:00 активным игрокам начисляется 50 Match-коинов. Новый пользователь получает право на первое начисление после входа в проект.' => 'Еженедельные начисления Match-коинов предусмотрены правилами проекта, но автоматическая выдача ещё готовится к запуску.',
    'Every Monday at 12:00, active players receive 50 Match coins. A new user qualifies for the first reward after entering the project.' => 'Weekly Match coin rewards are part of the project rules, but automatic distribution is still being prepared.',
    'Для последующих начислений необходимо сыграть не менее трёх матчей за квалификационную неделю. Коины добавляются отдельной операцией, которую можно увидеть в истории.' => 'После запуска условия активности будут отображаться в правилах Match-комнаты, а начисления — отдельными операциями в истории.',
    'To receive future rewards, play at least three matches during the qualifying week. Coins are added as a separate operation visible in history.' => 'After launch, activity requirements will be shown in the Match room rules and rewards will appear as separate history operations.',
    'Как сыграть с другом?' => 'Когда появятся приглашения друзьям?',
    'How do I play with a friend?' => 'When will friend invitations be available?',
    'Создайте матч и нажмите «Пригласить друга». Telegram сформирует приглашение, которое можно отправить нужному человеку прямо в чате.' => 'Кнопка приглашения уже предусмотрена в интерфейсе, но создание и отправка дружеских матчей пока не подключены.',
    'Create a match and choose “Invite a friend.” Telegram generates an invitation that can be sent directly in chat.' => 'An invitation button is already present in the interface, but creating and sending friend matches is not connected yet.',
    'Друг открывает приглашение, входит в тот же игровой формат и присоединяется к созданной комнате. Условия матча фиксируются до начала игры.' => 'До запуска функции используйте обычный поиск соперника. О появлении приглашений будет сообщено в обновлениях проекта.',
    'Your friend opens the invitation, enters the same game format and joins the created room. Match conditions are fixed before the game starts.' => 'Until the feature launches, use standard matchmaking. Friend invitations will be announced in a project update.',
    'Если поиск затягивается, можно выйти из очереди и выбрать другой формат или активную ставку.' => 'Если поиск затягивается, можно выйти из очереди и выбрать другие условия. В Match-комнате после ожидания система может создать матч с игровым ботом.',
    'If matchmaking takes too long, you can leave the queue and choose another format or active stake.' => 'If matchmaking takes too long, you can leave the queue and choose different conditions. In the Match room, the system may create a bot match after a wait.',
    'Пошагово объясняем, как открыть Mini App, создать матч и отправить другу приглашение.' => 'Объясняем, что уже работает в матчмейкинге и как будет устроена будущая функция приглашений.',
    'A step-by-step guide to opening the Mini App, creating a match and inviting a friend.' => 'A guide to current matchmaking and the planned friend invitation feature.',
    'Игровая платформа внутри Telegram для быстрых матчей один на один, приглашений друзей, истории игр и новых соревновательных режимов.' => 'Игровая платформа внутри Telegram для быстрых матчей один на один, истории игр и новых соревновательных режимов.',
    'A Telegram gaming platform for quick one-on-one matches, friend invitations, match history and new competitive modes.' => 'A Telegram gaming platform for quick one-on-one matches, match history and new competitive modes.',
    'Сервис работает' => 'Доступно в Telegram',
    'Service online' => 'Available in Telegram',
    '3×3 · 6×6 · 9×9' => '3×3 · 5×5 · 9×9',
    '3×3, 6×6 или 9×9' => '3×3, 5×5 или 9×9',
    '3×3, 6×6 and 9×9' => '3×3, 5×5 and 9×9',
    '3×3, 6×6 и 9×9' => '3×3, 5×5 и 9×9',
    '3×3, 6×6 or 9×9' => '3×3, 5×5 or 9×9',
    '3×3, 6×6 and 9×9 boards' => '3×3, 5×5 and 9×9 boards',
    '6×6' => '5×5',
    'Шахматы Blitz' => 'Блиц-шахматы',
];

$html = strtr($html, $replacements);

$oldStatus = '<aside class="live"><h3>🟢 <span class="i18n" data-lang="ru">Живой статус</span><span class="i18n" data-lang="en">Live status</span></h3><div class="liveRow"><span>Mini App</span><b class="ok">Online</b></div><div class="liveRow"><span>Telegram Bot</span><b class="ok">Online</b></div><div class="liveRow"><span>Server</span><b class="ok">Online</b></div></aside>';
$newStatus = '<aside class="live"><h3>ℹ️ <span class="i18n" data-lang="ru">Доступность</span><span class="i18n" data-lang="en">Availability</span></h3><div class="liveRow"><span>Mini App</span><b class="ok"><span class="i18n" data-lang="ru">Через Telegram</span><span class="i18n" data-lang="en">Via Telegram</span></b></div><div class="liveRow"><span>Telegram Bot</span><b class="ok"><span class="i18n" data-lang="ru">Точка входа</span><span class="i18n" data-lang="en">Entry point</span></b></div><div class="liveRow"><span>Server</span><b><span class="i18n" data-lang="ru">Без публичного статуса</span><span class="i18n" data-lang="en">No public status</span></b></div></aside>';
$html = str_replace($oldStatus, $newStatus, $html);

header('Content-Type: text/html; charset=UTF-8');
echo $html;
