<?php
ob_start();
require __DIR__ . '/landing-v8.php';
$html = ob_get_clean();

/*
 * Landing v9
 * - Keeps all existing public-site sections from v8.
 * - Replaces only the marketing hero with an up-to-date product presentation.
 * - Restyles the public header to match the Mini App palette.
 * - Does not touch /app or /bot.
 */

$heroCss = <<<'CSS'
<style id="hero-v10-styles">
:root{
  --mgw-app-bg:#090c14;
  --mgw-app-bg-2:#111827;
  --mgw-app-card:#151b2b;
  --mgw-app-card-2:#1b2336;
  --mgw-app-stroke:rgba(255,255,255,.09);
  --mgw-app-text:#f7f8fb;
  --mgw-app-muted:#a7b0c2;
  --mgw-app-soft:#cfd6e6;
  --mgw-app-accent:#7c5cff;
  --mgw-app-accent-dark:#5d42df;
  --mgw-app-green:#2ee6a6;
  --mgw-app-green-dark:#1fba88;
  --mgw-app-gold:#ffc857;
  --mgw-app-danger:#ff5f6d;
}
.siteHeader{border-bottom-color:rgba(255,255,255,.075)!important;background:rgba(9,12,20,.82)!important;box-shadow:none!important}
.siteHeader.is-scrolled{border-bottom-color:rgba(124,92,255,.2)!important;background:rgba(9,12,20,.96)!important;box-shadow:0 16px 44px rgba(0,0,0,.3)!important}
.siteBrandMark{background:linear-gradient(145deg,var(--mgw-app-accent),var(--mgw-app-accent-dark))!important;box-shadow:0 12px 30px rgba(124,92,255,.24)!important}
.siteBrandMark:after{border-color:rgba(255,255,255,.18)!important}.siteBrandText small{color:#8e98ac!important}
.siteNavLink:after{background:linear-gradient(90deg,var(--mgw-app-accent),var(--mgw-app-green))!important}
.siteLang button.active,.mobileLang button.active{background:rgba(124,92,255,.2)!important;box-shadow:inset 0 0 0 1px rgba(124,92,255,.46),0 8px 20px rgba(31,24,73,.22)!important}
.sitePlay,.mobilePlay{background:linear-gradient(135deg,var(--mgw-app-accent),var(--mgw-app-accent-dark))!important;box-shadow:0 12px 30px rgba(124,92,255,.2)!important}
.sitePlay:hover,.sitePlay:focus-visible{box-shadow:0 17px 38px rgba(124,92,255,.3)!important}.menuButton{background:rgba(255,255,255,.035)!important}.mobileMenu,.mobileMenuPanel{background-color:rgba(9,12,20,.985)!important}
.heroV10{position:relative;isolation:isolate;padding:58px 0 54px!important;overflow:hidden}
.heroV10:before,.heroV10:after{content:"";position:absolute;z-index:-2;border-radius:50%;pointer-events:none}
.heroV10:before{width:760px;height:760px;top:-390px;right:-170px;background:radial-gradient(circle,rgba(124,92,255,.18) 0,rgba(124,92,255,.07) 43%,transparent 72%);filter:blur(6px)}
.heroV10:after{width:620px;height:620px;left:-340px;bottom:-390px;background:radial-gradient(circle,rgba(46,230,166,.11) 0,rgba(46,230,166,.035) 46%,transparent 72%)}
.heroV10Grid{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(390px,.82fr);align-items:center;gap:clamp(38px,5vw,82px)}
.heroV10Copy{position:relative;z-index:2;max-width:780px}.heroV10Eyebrow{display:inline-flex;align-items:center;gap:10px;min-height:36px;padding:0 14px;border:1px solid rgba(124,92,255,.24);border-radius:999px;background:rgba(124,92,255,.075);color:#cfc7ff;font-size:12px;font-weight:900;letter-spacing:.09em;text-transform:uppercase}
.heroV10EyebrowDot{width:8px;height:8px;border-radius:50%;background:var(--mgw-app-green);box-shadow:0 0 0 5px rgba(46,230,166,.1),0 0 20px rgba(46,230,166,.55)}
.heroV10 h1{max-width:820px;margin:22px 0 22px!important;padding:0!important;color:var(--mgw-app-text);font-size:clamp(48px,5.25vw,78px)!important;line-height:1.02!important;letter-spacing:-.058em!important}
.heroV10TitleAccent{display:inline-block;color:#bfb4ff;background:linear-gradient(90deg,#ddd7ff 0%,#9d8cff 44%,#67e6bd 100%);-webkit-background-clip:text;background-clip:text;-webkit-text-fill-color:transparent}
.heroV10Lead{max-width:690px;margin:0;color:var(--mgw-app-muted);font-size:18px;line-height:1.7}.heroV10Lead strong{color:#e9ecf5;font-weight:850}.heroV10Actions{display:flex;gap:12px;flex-wrap:wrap;margin-top:29px}
.heroV10Primary,.heroV10Secondary{display:inline-flex;align-items:center;justify-content:center;gap:9px;min-height:52px;padding:0 21px;border-radius:15px;font-size:14px;font-weight:950;transition:transform .22s ease,border-color .22s ease,background .22s ease,box-shadow .22s ease}
.heroV10Primary{border:1px solid rgba(255,255,255,.06);background:linear-gradient(135deg,var(--mgw-app-accent),var(--mgw-app-accent-dark));box-shadow:0 16px 38px rgba(67,48,170,.27)}
.heroV10Secondary{border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.035);color:#dde2ed}.heroV10Primary:hover,.heroV10Primary:focus-visible,.heroV10Secondary:hover,.heroV10Secondary:focus-visible{transform:translateY(-2px);outline:none}.heroV10Primary:hover,.heroV10Primary:focus-visible{box-shadow:0 20px 46px rgba(67,48,170,.38)}.heroV10Secondary:hover,.heroV10Secondary:focus-visible{border-color:rgba(124,92,255,.36);background:rgba(124,92,255,.08)}.heroV10PrimaryIcon{font-size:16px;line-height:1}
.heroV10Benefits{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:9px;margin-top:26px}.heroV10Benefit{display:grid;grid-template-columns:auto 1fr;align-items:center;gap:9px;min-height:58px;padding:10px 12px;border:1px solid rgba(255,255,255,.075);border-radius:16px;background:rgba(255,255,255,.025);color:#cfd5e2;font-size:11px;font-weight:800;line-height:1.35}.heroV10BenefitIcon{width:31px;height:31px;display:grid;place-items:center;border-radius:10px;background:rgba(124,92,255,.1);font-size:15px}.heroV10Benefit:nth-child(2) .heroV10BenefitIcon,.heroV10Benefit:nth-child(5) .heroV10BenefitIcon{background:rgba(46,230,166,.09)}.heroV10Benefit:nth-child(4) .heroV10BenefitIcon{background:rgba(255,200,87,.1)}
.heroV10Visual{position:relative;min-width:0}.mgwHeroDevice{position:relative;width:min(100%,448px);margin:0 auto;padding:10px;border:1px solid rgba(255,255,255,.13);border-radius:36px;background:linear-gradient(155deg,rgba(255,255,255,.12),rgba(255,255,255,.025));box-shadow:0 35px 90px rgba(0,0,0,.48),0 0 0 1px rgba(124,92,255,.04)}
.mgwHeroDevice:before{content:"";position:absolute;z-index:-1;inset:10% -18% -11% 12%;border-radius:50%;background:radial-gradient(circle,rgba(124,92,255,.17),rgba(46,230,166,.035) 42%,transparent 72%);filter:blur(28px)}.mgwHeroDeviceTop{position:absolute;z-index:5;top:17px;left:50%;width:86px;height:5px;border-radius:99px;background:rgba(255,255,255,.15);transform:translateX(-50%)}.mgwHeroViewport{overflow:hidden;border-radius:28px;background:var(--mgw-app-bg)}.mgwHeroTrack{display:flex;transition:transform .58s cubic-bezier(.22,.76,.22,1);will-change:transform}.mgwHeroSlide{flex:0 0 100%;min-width:0;min-height:600px;padding:25px 18px 18px;background:radial-gradient(circle at 9% 0,rgba(124,92,255,.16),transparent 31%),var(--mgw-app-bg)}.mgwHeroSlideInner{height:100%;display:flex;flex-direction:column}
.mgwHeroAppTop{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:20px}.mgwHeroUser{display:flex;align-items:center;gap:10px;min-width:0}.mgwHeroAvatar{width:40px;height:40px;display:grid;place-items:center;flex:0 0 auto;border-radius:13px;background:linear-gradient(145deg,var(--mgw-app-accent),var(--mgw-app-accent-dark));color:#fff;font-size:12px;font-weight:950}.mgwHeroUserCopy{min-width:0}.mgwHeroUserCopy b{display:block;overflow:hidden;text-overflow:ellipsis;font-size:12px;white-space:nowrap}.mgwHeroUserCopy>span{display:flex;align-items:center;gap:5px;margin-top:3px;color:#8fe8c7;font-size:9px;font-weight:800}.mgwHeroUserCopy>span:before{content:"";width:6px;height:6px;border-radius:50%;background:var(--mgw-app-green)}.mgwHeroTopActions{display:flex;gap:7px}.mgwHeroIconButton{width:34px;height:34px;display:grid;place-items:center;border:1px solid var(--mgw-app-stroke);border-radius:11px;background:#171d2d;color:#e9edf5;font-size:13px}
.mgwHeroScreenKicker{color:#9d90ff;font-size:9px;font-weight:950;letter-spacing:.12em;text-transform:uppercase}.mgwHeroScreenTitle{margin:7px 0 6px;font-size:24px;line-height:1.07;letter-spacing:-.04em}.mgwHeroScreenLead{margin:0 0 15px;color:var(--mgw-app-muted);font-size:10.5px;line-height:1.48}.mgwHeroRoomTabs{display:grid;grid-template-columns:1fr 1fr;gap:4px;padding:4px;border:1px solid var(--mgw-app-stroke);border-radius:13px;background:#121827}.mgwHeroRoomTab{padding:8px;text-align:center;border-radius:9px;color:#8994a9;font-size:10px;font-weight:900}.mgwHeroRoomTab.active{color:#fff;background:rgba(124,92,255,.18);box-shadow:inset 0 0 0 1px rgba(124,92,255,.25)}.mgwHeroRoomTab.gold.active{color:#ffe19b;background:rgba(255,200,87,.12);box-shadow:inset 0 0 0 1px rgba(255,200,87,.25)}.mgwHeroRoomCard{margin-top:10px;padding:13px;border:1px solid var(--mgw-app-stroke);border-radius:16px;background:var(--mgw-app-card)}.mgwHeroRoomHead{display:flex;align-items:center;justify-content:space-between;gap:10px}.mgwHeroRoomHead b{font-size:13px}.mgwHeroRoomHead span{color:var(--mgw-app-gold);font-size:10px;font-weight:950}.mgwHeroRoomCard p{margin:6px 0 10px;color:var(--mgw-app-muted);font-size:9px;line-height:1.45}.mgwHeroMiniButton{display:flex;align-items:center;justify-content:center;min-height:32px;border-radius:10px;background:linear-gradient(135deg,var(--mgw-app-accent),var(--mgw-app-accent-dark));color:#fff;font-size:10px;font-weight:950}.mgwHeroMiniButton.gold{background:linear-gradient(135deg,#d99a28,#aa6a10)}.mgwHeroSectionLabel{display:flex;align-items:end;justify-content:space-between;gap:10px;margin:14px 0 8px}.mgwHeroSectionLabel b{font-size:11px}.mgwHeroSectionLabel span{color:#7f8a9e;font-size:8px}.mgwHeroGameList{display:grid;grid-template-columns:1fr 1fr;gap:7px}.mgwHeroGameCard{display:flex;align-items:center;gap:8px;min-height:51px;padding:8px;border:1px solid var(--mgw-app-stroke);border-radius:13px;background:rgba(21,27,43,.92)}.mgwHeroGameCard:last-child{grid-column:1/-1}.mgwHeroGameIcon{width:32px;height:32px;display:grid;place-items:center;flex:0 0 auto;border-radius:10px;background:var(--mgw-app-card-2);font-size:14px}.mgwHeroGameCard b{display:block;font-size:9.5px}.mgwHeroGameCard small{display:block;margin-top:2px;color:#8994aa;font-size:7.5px}
.mgwHeroSetupCard{padding:14px;border:1px solid var(--mgw-app-stroke);border-radius:17px;background:var(--mgw-app-card)}.mgwHeroSelectedGame{display:flex;align-items:center;gap:11px}.mgwHeroSelectedGame .mgwHeroGameIcon{width:43px;height:43px;font-size:19px}.mgwHeroSelectedGame b{display:block;font-size:13px}.mgwHeroSelectedGame span{display:block;margin-top:3px;color:var(--mgw-app-muted);font-size:8.5px}.mgwHeroChoicesTitle{margin:13px 0 7px;color:#dfe4ef;font-size:9px;font-weight:900}.mgwHeroChoices{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.mgwHeroChoice{padding:8px 4px;text-align:center;border:1px solid var(--mgw-app-stroke);border-radius:10px;background:rgba(255,255,255,.025);color:#9ca6b9;font-size:8.5px;font-weight:850}.mgwHeroChoice.active{border-color:rgba(124,92,255,.5);background:rgba(124,92,255,.14);color:#fff}.mgwHeroChoice.gold.active{border-color:rgba(255,200,87,.45);background:rgba(255,200,87,.11);color:#ffe29d}.mgwHeroGamesStrip{display:grid;grid-template-columns:repeat(5,1fr);gap:5px;margin:12px 0}.mgwHeroGamePick{display:grid;place-items:center;min-height:42px;border:1px solid var(--mgw-app-stroke);border-radius:11px;background:rgba(255,255,255,.024);font-size:14px}.mgwHeroGamePick.active{border-color:rgba(124,92,255,.5);background:rgba(124,92,255,.14)}.mgwHeroSearchHint{display:flex;align-items:center;gap:8px;margin-top:10px;padding:10px;border-radius:12px;background:rgba(46,230,166,.06);color:#a9ead2;font-size:8.5px;line-height:1.4}.mgwHeroSearchHint i{width:7px;height:7px;flex:0 0 auto;border-radius:50%;background:var(--mgw-app-green);box-shadow:0 0 13px rgba(46,230,166,.65)}
.mgwHeroGameHeader{display:grid;grid-template-columns:1fr auto;align-items:center;gap:10px}.mgwHeroTurn{font-size:12px;font-weight:950}.mgwHeroTimer{min-width:42px;padding:8px;text-align:center;border:1px solid var(--mgw-app-stroke);border-radius:11px;background:var(--mgw-app-card);color:#fff;font-size:11px;font-weight:950}.mgwHeroPlayers{display:grid;grid-template-columns:1fr auto 1fr;align-items:center;gap:8px;margin:12px 0}.mgwHeroPlayer{display:flex;align-items:center;gap:7px;padding:8px;border:1px solid var(--mgw-app-stroke);border-radius:12px;background:var(--mgw-app-card)}.mgwHeroPlayer:last-child{justify-content:flex-end;text-align:right}.mgwHeroPlayerAvatar{width:29px;height:29px;display:grid;place-items:center;border-radius:9px;background:var(--mgw-app-card-2);font-size:8px;font-weight:950}.mgwHeroPlayer b{display:block;font-size:8.5px}.mgwHeroPlayer small{color:#8893a8;font-size:7px}.mgwHeroVs{color:#6f7a8f;font-size:8px;font-weight:950}.mgwHeroFourBoard{display:grid;grid-template-columns:repeat(7,1fr);gap:4px;padding:10px;border:1px solid rgba(124,92,255,.2);border-radius:17px;background:linear-gradient(145deg,#242c62,#171d42);box-shadow:inset 0 0 30px rgba(0,0,0,.2)}.mgwHeroFourCell{aspect-ratio:1;border-radius:50%;background:#090d1e;box-shadow:inset 0 2px 4px rgba(0,0,0,.5)}.mgwHeroFourCell.red{background:#ff6573;box-shadow:inset 0 2px 5px rgba(255,255,255,.22),0 4px 10px rgba(255,95,109,.18)}.mgwHeroFourCell.yellow{background:#ffc857;box-shadow:inset 0 2px 5px rgba(255,255,255,.25),0 4px 10px rgba(255,200,87,.18)}.mgwHeroGameNote{margin-top:11px;padding:10px;border:1px solid var(--mgw-app-stroke);border-radius:12px;background:rgba(255,255,255,.025);color:#aeb7c8;font-size:8.5px;line-height:1.45}.mgwHeroGameFooter{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:auto;padding-top:12px}.mgwHeroGameFooter div{padding:9px;border:1px solid var(--mgw-app-stroke);border-radius:11px;background:var(--mgw-app-card);text-align:center}.mgwHeroGameFooter b{display:block;font-size:9px}.mgwHeroGameFooter span{display:block;margin-top:3px;color:#8994aa;font-size:7px}
.mgwHeroStoreBalance{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:14px;border:1px solid rgba(255,200,87,.18);border-radius:16px;background:linear-gradient(145deg,rgba(255,200,87,.11),rgba(21,27,43,.94))}.mgwHeroStoreBalance span{display:block;color:#d8c28f;font-size:8px}.mgwHeroStoreBalance strong{display:block;margin-top:3px;color:#ffe19b;font-size:19px}.mgwHeroStoreBalance small{color:#9f9272;font-size:7.5px}.mgwHeroCountryTabs{display:flex;gap:6px;margin:12px 0 8px}.mgwHeroCountry{padding:7px 9px;border:1px solid var(--mgw-app-stroke);border-radius:9px;background:rgba(255,255,255,.025);color:#8c96a9;font-size:8px;font-weight:900}.mgwHeroCountry.active{border-color:rgba(255,200,87,.35);background:rgba(255,200,87,.1);color:#ffe29c}.mgwHeroStoreGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.mgwHeroPrize{padding:10px;border:1px solid var(--mgw-app-stroke);border-radius:14px;background:var(--mgw-app-card)}.mgwHeroPrizeVisual{height:55px;display:grid;place-items:center;border-radius:11px;background:linear-gradient(145deg,#202a42,#141a2a);font-size:21px}.mgwHeroPrize b{display:block;margin-top:8px;font-size:9px}.mgwHeroPrize span{display:block;margin-top:3px;color:#8d98ac;font-size:7.5px}.mgwHeroPrize em{display:inline-flex;margin-top:7px;padding:4px 6px;border-radius:99px;background:rgba(46,230,166,.08);color:#84eac5;font-size:6.8px;font-style:normal;font-weight:900}.mgwHeroOrderEntry{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-top:9px;padding:11px;border:1px solid var(--mgw-app-stroke);border-radius:13px;background:rgba(255,255,255,.025)}.mgwHeroOrderEntry b{font-size:9px}.mgwHeroOrderEntry span{display:block;margin-top:2px;color:#8994aa;font-size:7px}.mgwHeroOrderEntry strong{width:22px;height:22px;display:grid;place-items:center;border-radius:8px;background:rgba(124,92,255,.13);color:#c7bfff;font-size:11px}
.mgwHeroSliderControls{display:flex;align-items:center;justify-content:center;gap:12px;margin-top:14px}.mgwHeroArrow{width:35px;height:35px;display:grid;place-items:center;padding:0;border:1px solid rgba(255,255,255,.1);border-radius:12px;background:rgba(255,255,255,.035);color:#e9edf5;cursor:pointer;transition:.2s}.mgwHeroArrow:hover,.mgwHeroArrow:focus-visible{border-color:rgba(124,92,255,.42);background:rgba(124,92,255,.1);outline:none}.mgwHeroDots{display:flex;align-items:center;gap:6px}.mgwHeroDot{width:7px;height:7px;padding:0;border:0;border-radius:99px;background:#3b4354;cursor:pointer;transition:width .25s ease,background .25s ease}.mgwHeroDot.active{width:22px;background:var(--mgw-app-accent)}.mgwHeroSliderCaption{min-height:36px;margin-top:9px;text-align:center;color:#8792a7;font-size:10px;line-height:1.45}.mgwHeroSliderCaption b{color:#dce1ec}
@media(max-width:1120px){.heroV10Grid{grid-template-columns:minmax(0,1fr) 390px;gap:38px}.heroV10 h1{font-size:clamp(44px,5.6vw,68px)!important}.heroV10Benefits{grid-template-columns:repeat(2,minmax(0,1fr))}}
@media(max-width:900px){.heroV10{padding-top:44px!important}.heroV10Grid{grid-template-columns:1fr;gap:44px}.heroV10Copy{max-width:760px;text-align:center;margin:auto}.heroV10Eyebrow{margin:auto}.heroV10Lead{margin-left:auto;margin-right:auto}.heroV10Actions{justify-content:center}.heroV10Benefits{max-width:690px;margin-left:auto;margin-right:auto;text-align:left}.mgwHeroDevice{width:min(100%,460px)}}
@media(max-width:640px){.heroV10{padding:34px 0 42px!important}.heroV10 h1{font-size:clamp(39px,12vw,56px)!important;line-height:1.04!important;margin-top:18px!important}.heroV10Lead{font-size:15px;line-height:1.65}.heroV10Actions{display:grid;grid-template-columns:1fr}.heroV10Primary,.heroV10Secondary{width:100%}.heroV10Benefits{grid-template-columns:1fr 1fr;gap:7px}.heroV10Benefit{min-height:62px;padding:9px;font-size:10px}.heroV10BenefitIcon{width:29px;height:29px}.mgwHeroDevice{padding:7px;border-radius:30px}.mgwHeroViewport{border-radius:24px}.mgwHeroSlide{min-height:570px;padding:23px 14px 15px}.mgwHeroSliderControls{margin-top:12px}}
@media(max-width:390px){.heroV10Benefits{grid-template-columns:1fr}.mgwHeroSlide{min-height:555px}}
@media(prefers-reduced-motion:reduce){.mgwHeroTrack,.heroV10Primary,.heroV10Secondary,.mgwHeroDot,.mgwHeroArrow{transition:none!important}}
.gamesShowcase::before{inset:auto!important;top:-110px!important;right:-190px!important;width:min(1080px,78vw)!important;height:780px!important;border-radius:50%!important;background:radial-gradient(ellipse at center,rgba(124,92,255,.12) 0%,rgba(124,92,255,.07) 30%,rgba(46,230,166,.025) 54%,transparent 76%)!important;filter:blur(18px);transform:translateZ(0);pointer-events:none}
@media(max-width:900px){.gamesShowcase::before{top:-40px!important;right:-300px!important;width:900px!important;height:700px!important;opacity:.82}}
</style>
CSS;

$fourCells = '';
$redCells = [23, 30, 31, 36, 37, 38];
$yellowCells = [24, 25, 32, 33, 39, 40, 41];
for ($cell = 0; $cell < 42; $cell++) {
    $class = 'mgwHeroFourCell';
    if (in_array($cell, $redCells, true)) $class .= ' red';
    elseif (in_array($cell, $yellowCells, true)) $class .= ' yellow';
    $fourCells .= '<span class="' . $class . '"></span>';
}

$heroSection = <<<HTML
<section class="hero heroV10" id="top" aria-labelledby="hero-v10-title"><div class="wrap"><div class="heroV10Grid"><div class="heroV10Copy">
<div class="heroV10Eyebrow"><span class="heroV10EyebrowDot" aria-hidden="true"></span><span class="i18n" data-lang="ru">Пять игр уже доступны</span><span class="i18n" data-lang="en">Five games available now</span></div>
<h1 id="hero-v10-title"><span class="i18n" data-lang="ru">Пять классических игр.<br><span class="heroV10TitleAccent">Один мир в Telegram.</span></span><span class="i18n" data-lang="en">Five classic games.<br><span class="heroV10TitleAccent">One world in Telegram.</span></span></h1>
<p class="heroV10Lead"><span class="i18n" data-lang="ru"><strong>Mini Games World</strong> — быстрые матчи со случайными соперниками и друзьями, две игровые комнаты, личная статистика и магазин сертификатов прямо внутри Telegram.</span><span class="i18n" data-lang="en"><strong>Mini Games World</strong> brings quick matches with random opponents and friends, two game rooms, personal statistics and a gift-card store directly into Telegram.</span></p>
<div class="heroV10Actions"><a class="heroV10Primary" href="https://t.me/MiniGamesWorld_bot" target="_blank" rel="noopener noreferrer"><span class="heroV10PrimaryIcon" aria-hidden="true">▶</span><span class="i18n" data-lang="ru">Играть в Telegram</span><span class="i18n" data-lang="en">Play in Telegram</span></a><a class="heroV10Secondary" href="#games"><span class="i18n" data-lang="ru">Посмотреть все игры</span><span class="i18n" data-lang="en">Explore all games</span><span aria-hidden="true">↓</span></a></div>
<div class="heroV10Benefits" aria-label="Преимущества Mini Games World"><div class="heroV10Benefit"><span class="heroV10BenefitIcon">🎮</span><span><span class="i18n" data-lang="ru">5 доступных игр</span><span class="i18n" data-lang="en">5 playable games</span></span></div><div class="heroV10Benefit"><span class="heroV10BenefitIcon">⚔️</span><span><span class="i18n" data-lang="ru">Match и Gold</span><span class="i18n" data-lang="en">Match and Gold</span></span></div><div class="heroV10Benefit"><span class="heroV10BenefitIcon">👥</span><span><span class="i18n" data-lang="ru">Соперник или друг</span><span class="i18n" data-lang="en">Opponent or friend</span></span></div><div class="heroV10Benefit"><span class="heroV10BenefitIcon">🎁</span><span><span class="i18n" data-lang="ru">Магазин сертификатов</span><span class="i18n" data-lang="en">Gift-card store</span></span></div><div class="heroV10Benefit"><span class="heroV10BenefitIcon">📊</span><span><span class="i18n" data-lang="ru">Профиль и история</span><span class="i18n" data-lang="en">Profile and history</span></span></div><div class="heroV10Benefit"><span class="heroV10BenefitIcon">⚡</span><span><span class="i18n" data-lang="ru">Без установки</span><span class="i18n" data-lang="en">No installation</span></span></div></div>
</div><div class="heroV10Visual"><div class="mgwHeroDevice" data-mgw-hero-slider aria-label="Интерактивный обзор Mini Games World"><span class="mgwHeroDeviceTop"></span><div class="mgwHeroViewport"><div class="mgwHeroTrack">
<article class="mgwHeroSlide" data-slide-title-ru="Главная с пятью играми" data-slide-title-en="Home with five games"><div class="mgwHeroSlideInner"><div class="mgwHeroAppTop"><div class="mgwHeroUser"><div class="mgwHeroAvatar">MG</div><div class="mgwHeroUserCopy"><b>@player_demo</b><span><span class="i18n" data-lang="ru">онлайн</span><span class="i18n" data-lang="en">online</span></span></div></div><div class="mgwHeroTopActions"><span class="mgwHeroIconButton">🔔</span><span class="mgwHeroIconButton">⋯</span></div></div><div class="mgwHeroScreenKicker">Mini Games World</div><h2 class="mgwHeroScreenTitle"><span class="i18n" data-lang="ru">Мировые мини-игры</span><span class="i18n" data-lang="en">Mini Games World</span></h2><p class="mgwHeroScreenLead"><span class="i18n" data-lang="ru">Быстрые матчи, друзья и победы в одном профиле.</span><span class="i18n" data-lang="en">Quick matches, friends and wins in one profile.</span></p><div class="mgwHeroRoomTabs"><div class="mgwHeroRoomTab active">Match</div><div class="mgwHeroRoomTab">Gold</div></div><div class="mgwHeroRoomCard"><div class="mgwHeroRoomHead"><b><span class="i18n" data-lang="ru">Матч-комната</span><span class="i18n" data-lang="en">Match room</span></b><span>10 coins</span></div><p><span class="i18n" data-lang="ru">Обычная комната для быстрых матчей.</span><span class="i18n" data-lang="en">The regular room for quick matches.</span></p><div class="mgwHeroMiniButton"><span class="i18n" data-lang="ru">Подробнее</span><span class="i18n" data-lang="en">Learn more</span></div></div><div class="mgwHeroSectionLabel"><b><span class="i18n" data-lang="ru">Игры</span><span class="i18n" data-lang="en">Games</span></b><span>5 <span class="i18n" data-lang="ru">доступно</span><span class="i18n" data-lang="en">available</span></span></div><div class="mgwHeroGameList"><div class="mgwHeroGameCard"><span class="mgwHeroGameIcon">✕○</span><div><b><span class="i18n" data-lang="ru">Крестики-нолики</span><span class="i18n" data-lang="en">Tic-tac-toe</span></b><small>3×3 · 5×5 · 9×9</small></div></div><div class="mgwHeroGameCard"><span class="mgwHeroGameIcon">🔴🟡</span><div><b><span class="i18n" data-lang="ru">4 в ряд</span><span class="i18n" data-lang="en">Four in a row</span></b><small>6×5 · 7×6 · 8×7</small></div></div><div class="mgwHeroGameCard"><span class="mgwHeroGameIcon">⚓</span><div><b><span class="i18n" data-lang="ru">Морской бой</span><span class="i18n" data-lang="en">Battleship</span></b><small>10×10</small></div></div><div class="mgwHeroGameCard"><span class="mgwHeroGameIcon">⚪</span><div><b><span class="i18n" data-lang="ru">Шашки</span><span class="i18n" data-lang="en">Checkers</span></b><small>8×8</small></div></div><div class="mgwHeroGameCard"><span class="mgwHeroGameIcon">◐</span><div><b><span class="i18n" data-lang="ru">Реверси</span><span class="i18n" data-lang="en">Reversi</span></b><small>6×6 · 8×8 · 10×10</small></div></div></div></div></article>
<article class="mgwHeroSlide" data-slide-title-ru="Выбор игры, комнаты и ставки" data-slide-title-en="Choose a game, room and stake"><div class="mgwHeroSlideInner"><div class="mgwHeroAppTop"><div><div class="mgwHeroScreenKicker"><span class="i18n" data-lang="ru">Настройка матча</span><span class="i18n" data-lang="en">Match setup</span></div><h2 class="mgwHeroScreenTitle"><span class="i18n" data-lang="ru">Выберите условия</span><span class="i18n" data-lang="en">Choose your match</span></h2></div><span class="mgwHeroIconButton">×</span></div><p class="mgwHeroScreenLead"><span class="i18n" data-lang="ru">Оба игрока начинают с одинаковой игрой, полем и ставкой.</span><span class="i18n" data-lang="en">Both players enter with the same game, board and stake.</span></p><div class="mgwHeroGamesStrip"><span class="mgwHeroGamePick">✕○</span><span class="mgwHeroGamePick active">🔴🟡</span><span class="mgwHeroGamePick">⚓</span><span class="mgwHeroGamePick">⚪</span><span class="mgwHeroGamePick">◐</span></div><div class="mgwHeroSetupCard"><div class="mgwHeroSelectedGame"><span class="mgwHeroGameIcon">🔴🟡</span><div><b><span class="i18n" data-lang="ru">4 в ряд</span><span class="i18n" data-lang="en">Four in a row</span></b><span><span class="i18n" data-lang="ru">Соберите четыре фишки раньше соперника.</span><span class="i18n" data-lang="en">Connect four pieces before your opponent.</span></span></div></div><div class="mgwHeroChoicesTitle"><span class="i18n" data-lang="ru">Комната</span><span class="i18n" data-lang="en">Room</span></div><div class="mgwHeroRoomTabs"><div class="mgwHeroRoomTab">Match</div><div class="mgwHeroRoomTab gold active">Gold</div></div><div class="mgwHeroChoicesTitle"><span class="i18n" data-lang="ru">Поле</span><span class="i18n" data-lang="en">Board</span></div><div class="mgwHeroChoices"><span class="mgwHeroChoice">6×5</span><span class="mgwHeroChoice active">7×6</span><span class="mgwHeroChoice">8×7</span></div><div class="mgwHeroChoicesTitle"><span class="i18n" data-lang="ru">Стоимость участия</span><span class="i18n" data-lang="en">Entry stake</span></div><div class="mgwHeroChoices"><span class="mgwHeroChoice gold">10</span><span class="mgwHeroChoice gold active">30 Gold</span><span class="mgwHeroChoice gold">100</span></div><div class="mgwHeroSearchHint"><i></i><span><span class="i18n" data-lang="ru">Найдём соперника с теми же условиями или создадим приглашение для друга.</span><span class="i18n" data-lang="en">Find an opponent with the same conditions or invite a friend.</span></span></div></div><div class="mgwHeroMiniButton gold" style="margin-top:auto;min-height:38px"><span class="i18n" data-lang="ru">Начать поиск</span><span class="i18n" data-lang="en">Start matchmaking</span></div></div></article>
<article class="mgwHeroSlide" data-slide-title-ru="Полноценная игровая партия" data-slide-title-en="A complete live match"><div class="mgwHeroSlideInner"><div class="mgwHeroGameHeader"><div><div class="mgwHeroScreenKicker"><span class="i18n" data-lang="ru">Gold-комната · 30 Gold</span><span class="i18n" data-lang="en">Gold room · 30 Gold</span></div><div class="mgwHeroTurn"><span class="i18n" data-lang="ru">Ваш ход</span><span class="i18n" data-lang="en">Your turn</span></div></div><div class="mgwHeroTimer">00:42</div></div><div class="mgwHeroPlayers"><div class="mgwHeroPlayer"><span class="mgwHeroPlayerAvatar">MG</span><div><b><span class="i18n" data-lang="ru">Вы</span><span class="i18n" data-lang="en">You</span></b><small><span class="i18n" data-lang="ru">красные</span><span class="i18n" data-lang="en">red</span></small></div></div><div class="mgwHeroVs">VS</div><div class="mgwHeroPlayer"><div><b>@opponent</b><small><span class="i18n" data-lang="ru">жёлтые</span><span class="i18n" data-lang="en">yellow</span></small></div><span class="mgwHeroPlayerAvatar">OP</span></div></div><div class="mgwHeroFourBoard" aria-label="Демонстрационное поле игры 4 в ряд">{$fourCells}</div><div class="mgwHeroGameNote"><span class="i18n" data-lang="ru">Фишка падает в выбранный столбец. Соберите четыре подряд по горизонтали, вертикали или диагонали.</span><span class="i18n" data-lang="en">A piece drops into the selected column. Connect four horizontally, vertically or diagonally.</span></div><div class="mgwHeroGameFooter"><div><b><span class="i18n" data-lang="ru">Матч хранится на сервере</span><span class="i18n" data-lang="en">Server-side match state</span></b><span><span class="i18n" data-lang="ru">результат не потеряется</span><span class="i18n" data-lang="en">your result stays safe</span></span></div><div><b><span class="i18n" data-lang="ru">История обновится</span><span class="i18n" data-lang="en">History is updated</span></b><span><span class="i18n" data-lang="ru">после завершения</span><span class="i18n" data-lang="en">after the match</span></span></div></div></div></article>
<article class="mgwHeroSlide" data-slide-title-ru="Gold-магазин и история заявок" data-slide-title-en="Gold store and order history"><div class="mgwHeroSlideInner"><div class="mgwHeroAppTop"><div><div class="mgwHeroScreenKicker"><span class="i18n" data-lang="ru">Gold-комната</span><span class="i18n" data-lang="en">Gold room</span></div><h2 class="mgwHeroScreenTitle"><span class="i18n" data-lang="ru">Магазин призов</span><span class="i18n" data-lang="en">Rewards store</span></h2></div><span class="mgwHeroIconButton">×</span></div><p class="mgwHeroScreenLead"><span class="i18n" data-lang="ru">Выберите страну, сертификат и доступный номинал.</span><span class="i18n" data-lang="en">Choose a country, gift card and available value.</span></p><div class="mgwHeroStoreBalance"><div><span><span class="i18n" data-lang="ru">Доступно для магазина</span><span class="i18n" data-lang="en">Available in store</span></span><strong>2 450 Gold</strong></div><small><span class="i18n" data-lang="ru">Баланс: 3 120</span><span class="i18n" data-lang="en">Balance: 3,120</span></small></div><div class="mgwHeroCountryTabs"><span class="mgwHeroCountry active"><span class="i18n" data-lang="ru">Польша</span><span class="i18n" data-lang="en">Poland</span></span><span class="mgwHeroCountry"><span class="i18n" data-lang="ru">Европа</span><span class="i18n" data-lang="en">Europe</span></span></div><div class="mgwHeroStoreGrid"><div class="mgwHeroPrize"><div class="mgwHeroPrizeVisual">🎮</div><b>Gaming Card</b><span><span class="i18n" data-lang="ru">Электронный сертификат</span><span class="i18n" data-lang="en">Digital gift card</span></span><em>1 000 Gold</em></div><div class="mgwHeroPrize"><div class="mgwHeroPrizeVisual">🛍️</div><b>Marketplace</b><span><span class="i18n" data-lang="ru">Сертификат магазина</span><span class="i18n" data-lang="en">Store gift card</span></span><em>2 000 Gold</em></div></div><div class="mgwHeroOrderEntry"><div><b><span class="i18n" data-lang="ru">Мои заявки</span><span class="i18n" data-lang="en">My orders</span></b><span><span class="i18n" data-lang="ru">Статусы, причины и возвраты Gold</span><span class="i18n" data-lang="en">Statuses, reasons and Gold refunds</span></span></div><strong>3</strong></div><div class="mgwHeroSetupCard" style="margin-top:9px"><div class="mgwHeroChoicesTitle" style="margin-top:0"><span class="i18n" data-lang="ru">Выбранный номинал</span><span class="i18n" data-lang="en">Selected value</span></div><div class="mgwHeroChoices"><span class="mgwHeroChoice gold">1 000</span><span class="mgwHeroChoice gold active">2 000</span><span class="mgwHeroChoice gold">3 000</span></div></div><div class="mgwHeroMiniButton gold" style="margin-top:auto;min-height:38px"><span class="i18n" data-lang="ru">Продолжить</span><span class="i18n" data-lang="en">Continue</span></div></div></article>
</div></div><div class="mgwHeroSliderControls"><button class="mgwHeroArrow" type="button" data-mgw-prev aria-label="Предыдущий экран">←</button><div class="mgwHeroDots" role="tablist"><button class="mgwHeroDot active" type="button" data-mgw-dot="0" aria-label="Экран 1" aria-selected="true"></button><button class="mgwHeroDot" type="button" data-mgw-dot="1" aria-label="Экран 2" aria-selected="false"></button><button class="mgwHeroDot" type="button" data-mgw-dot="2" aria-label="Экран 3" aria-selected="false"></button><button class="mgwHeroDot" type="button" data-mgw-dot="3" aria-label="Экран 4" aria-selected="false"></button></div><button class="mgwHeroArrow" type="button" data-mgw-next aria-label="Следующий экран">→</button></div><div class="mgwHeroSliderCaption" aria-live="polite"><b data-mgw-caption-number>01 / 04</b> · <span data-mgw-caption-text>Главная с пятью играми</span></div></div></div></div></div></section>
HTML;

$heroScript = <<<'JS'
<script id="hero-v10-script">
(function(){'use strict';var root=document.querySelector('[data-mgw-hero-slider]');if(!root)return;var track=root.querySelector('.mgwHeroTrack');var slides=Array.prototype.slice.call(root.querySelectorAll('.mgwHeroSlide'));var dots=Array.prototype.slice.call(root.querySelectorAll('[data-mgw-dot]'));var prev=root.querySelector('[data-mgw-prev]');var next=root.querySelector('[data-mgw-next]');var number=root.querySelector('[data-mgw-caption-number]');var caption=root.querySelector('[data-mgw-caption-text]');var reduced=window.matchMedia&&window.matchMedia('(prefers-reduced-motion: reduce)').matches;var current=0,timer=null,pointerStart=null;function language(){return document.documentElement.lang==='en'?'en':'ru'}function setCaption(slide){if(caption)caption.textContent=slide.getAttribute('data-slide-title-'+language())||slide.getAttribute('data-slide-title-ru')||''}function goTo(index,user){if(!slides.length)return;current=(index+slides.length)%slides.length;track.style.transform='translate3d(-'+current*100+'%,0,0)';slides.forEach(function(slide,i){slide.setAttribute('aria-hidden',i===current?'false':'true')});dots.forEach(function(dot,i){var active=i===current;dot.classList.toggle('active',active);dot.setAttribute('aria-selected',active?'true':'false');dot.setAttribute('tabindex',active?'0':'-1')});if(number)number.textContent=String(current+1).padStart(2,'0')+' / '+String(slides.length).padStart(2,'0');setCaption(slides[current]);if(user)restart()}function stop(){if(timer){clearInterval(timer);timer=null}}function start(){if(reduced||slides.length<2||timer)return;timer=setInterval(function(){goTo(current+1,false)},6200)}function restart(){stop();start()}if(prev)prev.addEventListener('click',function(){goTo(current-1,true)});if(next)next.addEventListener('click',function(){goTo(current+1,true)});dots.forEach(function(dot){dot.addEventListener('click',function(){goTo(Number(dot.getAttribute('data-mgw-dot')||0),true)})});root.addEventListener('mouseenter',stop);root.addEventListener('mouseleave',start);root.addEventListener('focusin',stop);root.addEventListener('focusout',function(e){if(!root.contains(e.relatedTarget))start()});root.addEventListener('pointerdown',function(e){if(e.pointerType==='mouse'&&e.button!==0)return;pointerStart={id:e.pointerId,x:e.clientX,y:e.clientY}});root.addEventListener('pointerup',function(e){if(!pointerStart||pointerStart.id!==e.pointerId)return;var dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;pointerStart=null;if(Math.abs(dx)>52&&Math.abs(dx)>Math.abs(dy))goTo(current+(dx<0?1:-1),true)});root.addEventListener('pointercancel',function(){pointerStart=null});document.addEventListener('visibilitychange',function(){document.visibilityState==='visible'?start():stop()});document.querySelectorAll('[data-lang-btn]').forEach(function(button){button.addEventListener('click',function(){setTimeout(function(){setCaption(slides[current])},0)})});goTo(0,false);start()})();
</script>
JS;

$updated = preg_replace('~<section class="hero">.*?</section>~s', $heroSection, $html, 1, $heroCount);
if ($updated === null || $heroCount !== 1) { http_response_code(500); echo 'Hero section could not be updated.'; exit; }
$html = $updated;
$html = preg_replace('~<title>.*?</title>~s', '<title>Mini Games World — 5 игр, Match, Gold и призы в Telegram</title>', $html, 1);
$html = preg_replace('~<meta name="description" content="[^"]*">~', '<meta name="description" content="Пять игр в Telegram Mini App: Match и Gold-комнаты, случайные соперники, приглашения друзей, профиль, история матчей и магазин сертификатов.">', $html, 1);
$html = preg_replace('~<meta property="og:title" content="[^"]*">~', '<meta property="og:title" content="Mini Games World — пять игр и призы в Telegram">', $html, 1);
$html = preg_replace('~<meta property="og:description" content="[^"]*">~', '<meta property="og:description" content="Пять доступных игр, Match и Gold, матчи с друзьями, история и магазин сертификатов внутри Telegram.">', $html, 1);
if (strpos($html, 'hero-v10-styles') === false) $html = str_replace('</head>', $heroCss . '</head>', $html);
if (strpos($html, 'hero-v10-script') === false) $html = str_replace('</body>', $heroScript . '</body>', $html);
header('Content-Type: text/html; charset=UTF-8');
echo $html;
