<?php
declare(strict_types=1);

return [
    'version' => 'v2-route-scoped-polling',
    'imports' => [
        '@mgw/clean-entry' => './assets/js/production-clean-entry-v110.js?v=1127&mvp16=canonical-avatar-owner&mvp17=history-single-owner&mvp19=avatar-presentation&mvp19_4=character-identity&art=illustrated-raster&roster=portrait-v5',
        '@mgw/main' => './assets/js/main-v110-reconnect-v174.js?v=2',
        '@mgw/i18n' => './assets/js/localization/i18n.js?v=2&mvp16=account-locale-precedence',
        './assets/js/api/client.js?v=34' => './assets/js/api/client.js?v=1134&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot',
        './assets/js/api/client.js?v=38' => './assets/js/api/client.js?v=1134&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot',
        './assets/js/api/client.js?v=46' => './assets/js/api/client.js?v=1134&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot',
        './assets/js/api/client.js?v=47' => './assets/js/api/client.js?v=1134&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot',
        './assets/js/config.js?v=38' => './assets/js/config.js?v=39&mvp15=match-economy',
        './assets/js/state.js?v=27' => './assets/js/state.js?v=31&mvp16=router-lifecycle&mvp19=profile-inventory&mvp19_3_1=avatar-owner',
        './assets/js/router.js?v=27' => './assets/js/router.js?v=30&b=871cb833d99d&mvp16=route-registry&mvp18=friends',
        './assets/js/ui.js?v=89' => './assets/js/ui.js?v=95&mvp16=canonical-profile-display-owner&mvp19=mgw-avatar-only&mvp19_3_1=selected-avatar-owner',
        './assets/js/components/sheet.js?v=68' => './assets/js/components/sheet.js?v=1110&mvp16=nested-return',
        './assets/js/components/sheet.js?v=1109' => './assets/js/components/sheet.js?v=1110&mvp16=nested-return',
        './assets/js/components/account-shortcuts.js?v=48' => './assets/js/components/account-shortcuts.js?v=53&mvp18=instant-route&optimistic-relations',
        './assets/js/screens/home-screen.js?v=74' => './assets/js/screens/home-screen.js?v=80&mvp16=settings-row-owner&mvp17=match-history-economy&live=owner-v3&ux=ready-only-history-sheet&perf=prefetched-history',
        './assets/js/screens/store-screen.js?v=34' => './assets/js/screens/store-screen.js?v=43&mvp16=primary-tab&mvp19=store-v2&corrective=2&mvp19_3_1=optimistic-purchase&mvp19_4=purchase-avatar-preview&game_cosmetics=pilot-polish-v3',
        './assets/js/screens/profile-screen-v110.js?v=1108' => './assets/js/screens/profile-screen-v110.js?v=1119&mvp16=profile-pass-a&mvp17=result-history-economy&mvp19=avatar-collection&previsual=instant-equip&mvp19_3_1=avatar-sync',
        './assets/js/profile/mgw-profile-model.js?v=1' => './assets/js/profile/mgw-profile-model.js?v=4&mvp16=public-id-canonical-identity&mvp19_3_1=avatar-pass-through',
        './assets/js/main-v110-handoff-shell.js?v=1137&ux=1&sk=3&icons=c1efd5af&render=5' => './assets/js/main-v110-handoff-shell.js?v=1154&mvp18=friend-request-lifecycle',
        './assets/js/games/game-rules.js?v=75' => './assets/js/games/game-rules.js?v=78&mvp16=all-variant-rules',
        './assets/js/games/unified-game-launcher.js?v=1&mvp16=unified-game-setup' => './assets/js/games/unified-game-launcher.js?v=4&mvp16=setup-subtitle-width',
        './assets/js/session.js?v=21' => './assets/js/session.js?v=1131',
        './assets/js/session.js?v=27' => './assets/js/session.js?v=1131',
        './assets/js/screens/search-screen-v102.js?v=103' => './assets/js/screens/search-screen-v102.js?v=107&search=route-scoped-lifecycle',
        './assets/js/screens/game-screen-v102-safe.js?v=102' => './assets/js/screens/game-screen-v102-safe.js?v=104&polling=route-cleanup',
        './assets/js/screens/game-screen-v102.js?v=102' => './assets/js/screens/game-screen-v102.js?v=106&clock=phase-b-single-writer&battleship=leave-guard&mvp17=result-history-economy&live=owner-v3&result=compact-fast-v1',
        './assets/js/production-v100-optimistic-models.js?v=102' => './assets/js/production-v100-optimistic-models.js?v=104&clock=ttt-fresh60&battleship=registered-owner',
        './assets/js/production-v102-battleship-models.js?v=102' => './assets/js/production-v102-battleship-models.js?v=103&ready=authoritative-reset',
        './assets/js/production-v110-readonly-game-sync.js?v=1107&b=bc9d7b435f1a' => './assets/js/production-v110-readonly-game-sync.js?v=1112&terminal=nonblocking-watch',
        './assets/js/production-v110-targeted-interactions.js?v=1102' => './assets/js/production-v110-targeted-interactions.js?v=1105&zone=unified&ttt=single-owner',
        './assets/js/production-v110-presence.js?v=1121&b=f5a28b030c69' => './assets/js/production-v110-presence.js?v=1124&mvp17=reconnect-v2',
        './assets/js/games/game-invites-v110.js?v=1137&ux=1' => './assets/js/games/game-invites-v110-rematch-policy-v175.js?v=1&fp=2',
        './assets/js/games/game-invites-v110.js?v=1142&zone=unified&rematch=optimistic&terminal=self-silent' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe',
        './assets/js/games/game-invites-v110.js?v=1143&zone=unified&rematch=optimistic&terminal=self-silent&social=1' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe',
        './assets/js/games/game-invites-v110.js?v=1144&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe',
        './assets/js/games/tictactoe/renderer.js?v=53' => './assets/js/games/tictactoe/renderer.js?v=55&mark=full-size-nought&mvp19_4=game-cosmetics-pilot',
        './assets/js/games/battleship/renderer.js?v=56' => './assets/js/games/battleship/renderer.js?v=60&shot=miss-no-impact',
        './assets/js/production-v110-acceptance-runtime.js?v=110' => './assets/js/production-v110-acceptance-runtime.js?v=130&clock=battleship-setup-single-owner&launch=ready-gated-v2&terminal=clock-stable&input=first-tap-v1',
        './assets/js/components/shield-king-visuals.js?v=125&sk=2' => './assets/js/components/shield-king-visuals.js?v=129&sk=4&icons=c1efd5af&shell=nav&settings=metallic&friends=1',
        './assets/js/components/shield-king-visuals.js?v=127&sk=4&icons=c1efd5af&shell=nav' => './assets/js/components/shield-king-visuals.js?v=129&sk=4&icons=c1efd5af&shell=nav&settings=metallic&friends=1',
        './assets/js/components/preloader.js?v=42' => './assets/js/components/preloader.js?v=44&intro=v1141',
        './assets/js/games/game-card-copy.js?v=81&sk=2' => './assets/js/games/game-card-copy.js?v=83&sk=5&icons=c1efd5af&delivery=static',
    ],
    'assets' => [
        'main_css' => './assets/css/main.css?v=180&sk=3&icons=c1efd5af&render=39&mvp16=notification-center-v2-desktop-cache&mvp18=friends-corrective&mvp19=store-v2&corrective=2&avatar=profile-v1&avatar=character-v2&mvp19_4=character-identity&art=illustrated-raster&roster=portrait-v5&game_cosmetics=pilot-polish-v3&four=ios-fit',
        'consistency_css' => './assets/css/production-v95-consistency.css?v=96&battleship=pending-lock-only',
        'bootstrap' => './assets/js/app-bootstrap-v2.js?v=2&mvp16=version-manifest',
    ],
    'localization' => ['version'=>'keys-v1','default_locale'=>'ru','manifest'=>'./locales/manifest.json'],
];
