<?php
declare(strict_types=1);

return [
    'version' => 'v2-route-scoped-polling',
    'imports' => [
        '@mgw/clean-entry' => './assets/js/production-clean-entry-v110-mvp19-3-final-polish.js?v=1132&mvp16=canonical-avatar-owner&mvp17=history-single-owner&mvp19=avatar-presentation&mvp19_4=character-identity&art=illustrated-raster&roster=portrait-v5&mvp19_3=name-colors&mvp19_3_6=profile-badge-avatar-overlay&mvp19_3_7=profile-frames&mvp19_3_8=profile-frame-preview-polish&mvp19_3_9=badge-avatar-card&mvp19_3_10=profile-frame-name-polish&mvp19_3_11=profile-badge-avatar-shape&mvp19_3_12=profile-frame-avatar-card-parity&mvp19_3_15=profile-backgrounds&mvp19_3_16=profile-backgrounds-ux-corrective&mvp19_3_17=background-route-hydration&mvp19_3_20=avatar-store-action&mvp19_3_21=avatar-store-action-post-app-ready&mvp19_3_22=store-freeze-idempotent-decorator&mvp19_3_23=frame-avatar-actions&mvp19_3_24=profile-card-parity&profile_first=post-paint-effects&purchase=immediate-feedback&profile_route=exact-active-warm-v1&profile_route_guard=light-surface-v1',
        '@mgw/main' => './assets/js/main-v110-reconnect-v174.js?v=2',
        '@mgw/i18n' => './assets/js/localization/i18n.js?v=2&mvp16=account-locale-precedence',
        './assets/js/api/client.js?v=34' => './assets/js/api/client.js?v=1135&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot&c7=avatar-bootstrap-inventory&c2_1=effect-unequip&mvp19_3_4=name-color-live-projection&mvp19_3_7=profile-v2-read-coalesce&mvp19_3_28=reactions',
        './assets/js/api/client.js?v=38' => './assets/js/api/client.js?v=1135&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot&c7=avatar-bootstrap-inventory&c2_1=effect-unequip&mvp19_3_4=name-color-live-projection&mvp19_3_7=profile-v2-read-coalesce&mvp19_3_28=reactions',
        './assets/js/api/client.js?v=46' => './assets/js/api/client.js?v=1135&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot&c7=avatar-bootstrap-inventory&c2_1=effect-unequip&mvp19_3_4=name-color-live-projection&mvp19_3_7=profile-v2-read-coalesce&mvp19_3_28=reactions',
        './assets/js/api/client.js?v=47' => './assets/js/api/client.js?v=1135&mvp16=profile-corrective&mvp17=history-fresh-match&menu=fast-history&result=locked-watch&mvp18=friends&mvp19=store-v2&mvp19_4=game-cosmetics-pilot&c7=avatar-bootstrap-inventory&c2_1=effect-unequip&mvp19_3_4=name-color-live-projection&mvp19_3_7=profile-v2-read-coalesce&mvp19_3_28=reactions',
        './assets/js/config.js?v=38' => './assets/js/config.js?v=39&mvp15=match-economy',
        './assets/js/state.js?v=27' => './assets/js/state.js?v=31&mvp16=router-lifecycle&mvp19=profile-inventory&mvp19_3_1=avatar-owner',
        './assets/js/router.js?v=27' => './assets/js/router.js?v=32&profile_nav=direct-sync-v2',
        './assets/js/ui.js?v=89' => './assets/js/ui.js?v=97&mvp16=canonical-profile-display-owner&mvp19=mgw-avatar-only&mvp19_3_1=selected-avatar-owner&c7=no-false-starter&mvp19_3_4=name-color-chrome',
        './assets/js/components/sheet.js?v=68' => './assets/js/components/sheet.js?v=1110&mvp16=nested-return',
        './assets/js/components/sheet.js?v=1109' => './assets/js/components/sheet.js?v=1110&mvp16=nested-return',
        './assets/js/components/toast.js?v=27' => './assets/js/components/toast.js?v=28&store=quiet-equip',
        './assets/js/components/account-shortcuts.js?v=48' => './assets/js/components/account-shortcuts.js?v=53&mvp18=instant-route&optimistic-relations',
        './assets/js/screens/home-screen.js?v=74' => './assets/js/screens/home-screen.js?v=80&mvp16=settings-row-owner&mvp17=match-history-economy&live=owner-v3&ux=ready-only-history-sheet&perf=prefetched-history&startup=after-app-ready',
        './assets/js/screens/store-screen.js?v=34' => './assets/js/screens/store-screen-intent-wrapper.js?v=1&mobile=intent-only&mobile_scope=all&first_paint=preloader-primed-final-v1&first_refresh=single-render-v1&profile_first=settled-before-store-intent-v3&first_visible=consume-prime-no-refresh-v1',
        './assets/js/screens/profile-screen-v110.js?v=1108' => './assets/js/screens/profile-screen-v110.js?v=1126&mvp16=profile-pass-a&mvp17=result-history-economy&mvp19=avatar-collection&previsual=instant-equip&mvp19_3_1=avatar-sync&mvp19_3_2=game-cosmetics&mvp19_3_3=game-tabs-fresh&mvp19_3_4=name-colors&perf=stable-render-cache&active_refresh=deferred-remount-v1&entry=paint-cached-first-v1&mobile_lifecycle=yield-refresh-and-remount-v1',
        './assets/js/profile/mgw-profile-model.js?v=1' => './assets/js/profile/mgw-profile-model.js?v=5&mvp16=public-id-canonical-identity&mvp19_3_1=avatar-pass-through&c7=no-prehydrate-default',
        './assets/js/profile/mgw-profile-backgrounds.js?v=2&mvp19_3=profile-backgrounds-ux-corrective' => './assets/js/profile/mgw-profile-backgrounds.js?v=3&mvp19_3=full-profile-surface',
        './assets/js/profile/mgw-profile-reactions.js?v=1&mvp19_3=profile-reactions' => './assets/js/profile/mgw-profile-reactions-header.js?v=5&mvp19_3=header-square-smooth&mobile=stable-bubble-canonical-profile-nav&profile_nav=canonical-pointer-v2',
        './assets/js/profile/mgw-profile-reactions.js?v=2&mvp19_3=ingame-corrective-base' => './assets/js/profile/mgw-profile-reactions.js?v=6&mvp19_3=cumulative-owned-reactions&store=passive-owned&preview=bounded-packs-v2&route_work=game-only-v1',
        './assets/js/main-v110-handoff-shell.js?v=1137&ux=1&sk=3&icons=c1efd5af&render=5' => './assets/js/main-v110-handoff-shell.js?v=1156&mvp18=friend-request-lifecycle&store=post-boot-warm&profile=boot-prepared-direct-route-v1&profile_first=background-raster-prewarm-v1&tournaments=active-raster-prewarm-v1&store_first=sync-prerender-v2&store_warm=post-profile-safe-v2',
        './assets/js/games/game-rules.js?v=75' => './assets/js/games/game-rules.js?v=78&mvp16=all-variant-rules',
        './assets/js/games/unified-game-launcher.js?v=1&mvp16=unified-game-setup' => './assets/js/games/unified-game-launcher.js?v=4&mvp16=setup-subtitle-width',
        './assets/js/session.js?v=21' => './assets/js/session.js?v=1131',
        './assets/js/session.js?v=27' => './assets/js/session.js?v=1131',
        './assets/js/screens/search-screen-v102.js?v=103' => './assets/js/screens/search-screen-v102.js?v=107&search=route-scoped-lifecycle',
        './assets/js/screens/game-screen-v102-safe.js?v=102' => './assets/js/screens/game-screen-v102-safe.js?v=104&polling=route-cleanup',
        './assets/js/screens/game-screen-v102.js?v=102' => './assets/js/screens/game-screen-v102.js?v=106&clock=phase-b-single-writer&battleship=leave-guard&mvp17=result-history-economy&live=owner-v3&result=compact-fast-v1',
        './assets/js/production-v100-optimistic-models.js?v=102' => './assets/js/production-v100-optimistic-models.js?v=104&clock=ttt-fresh60&battleship=registered-owner',
        './assets/js/production-v102-battleship-models.js?v=102' => './assets/js/production-v102-battleship-models.js?v=103&ready=authoritative-reset',
        './assets/js/production-v110-readonly-game-sync.js?v=1107&b=bc9d7b435f1a' => './assets/js/production-v110-readonly-game-sync.js?v=1113&terminal=nonblocking-watch&mvp19_3=reactions',
        './assets/js/production-v110-targeted-interactions.js?v=1102' => './assets/js/production-v110-targeted-interactions.js?v=1105&zone=unified&ttt=single-owner',
        './assets/js/production-v110-presence.js?v=1121&b=f5a28b030c69' => './assets/js/production-v110-presence.js?v=1124&mvp17=reconnect-v2&heartbeat=lease-phase',
        './assets/js/games/game-invites-v110.js?v=1137&ux=1' => './assets/js/games/game-invites-v110-rematch-policy-v175.js?v=1&fp=2',
        './assets/js/games/game-invites-v110.js?v=1142&zone=unified&rematch=optimistic&terminal=self-silent' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe',
        './assets/js/games/game-invites-v110.js?v=1143&zone=unified&rematch=optimistic&terminal=self-silent&social=1' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe',
        './assets/js/games/game-invites-v110.js?v=1144&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native' => './assets/js/games/game-invites-v110.js?v=1145&zone=unified&rematch=optimistic&terminal=self-silent&social=1&share=telegram-native&waiting=draft-safe',
        './assets/js/games/tictactoe/renderer.js?v=53' => './assets/js/games/tictactoe/renderer.js?v=58&mark=full-size-nought&mvp19_4=game-cosmetics-pilot&c2=effects-v2&c2_1=mark-owned&c2_4=poll-persistent-effects&c2_5=visible-mark-layer&c2_6=cell-native-dom-fx',
        './assets/js/games/battleship/renderer.js?v=56' => './assets/js/games/battleship/renderer.js?v=60&shot=miss-no-impact',
        './assets/js/production-v110-acceptance-runtime.js?v=110' => './assets/js/production-v110-acceptance-runtime.js?v=130&clock=battleship-setup-single-owner&launch=ready-gated-v2&terminal=clock-stable&input=first-tap-v1',
        './assets/js/components/shield-king-visuals.js?v=125&sk=2' => './assets/js/components/shield-king-visuals.js?v=129&sk=4&icons=c1efd5af&shell=nav&settings=metallic&friends=1',
        './assets/js/components/shield-king-visuals.js?v=127&sk=4&icons=c1efd5af&shell=nav' => './assets/js/components/shield-king-visuals.js?v=129&sk=4&icons=c1efd5af&shell=nav&settings=metallic&friends=1',
        './assets/js/components/preloader.js?v=42' => './assets/js/components/preloader.js?v=45&intro=v1141&store_first=preloader-ready-v1',
        './assets/js/telegram/telegram-app.js?v=27' => './assets/js/telegram/telegram-app.js?v=28&haptic=preloader-silent-v1',
        './assets/js/games/game-card-copy.js?v=81&sk=2' => './assets/js/games/game-card-copy.js?v=83&sk=5&icons=c1efd5af&delivery=static',
    ],
    'assets' => [
        'main_css' => './assets/css/main.css?v=190&sk=3&icons=c1efd5af&render=42&mvp16=notification-center-v2-desktop-cache&mvp18=friends-corrective&mvp19=store-v2&corrective=2&avatar=profile-v1&avatar=character-v2&mvp19_4=character-identity&art=illustrated-raster&roster=portrait-v5&game_cosmetics=pilot-polish-v3&four=ios-fit&c1=ttt-field-parity&c2=effects-v2&c2_1=single-slot-parity&store=compact-tail&c2_5=visible-mark-layer&c2_6=cell-native-dom-fx&mvp19_3=profile-game-tabs-fresh&mvp19_3_4=name-colors-polish&mvp19_3_5=compact-name-colors-instant-profile&spacing=name-color-price-button&mvp19_3_6=profile-badge-avatar-overlay&badge_position=bottom-right&badge_collection=fit&badge_store=avatar-card&mvp19_3_7=profile-frames&frame_preview=avatar-card&mvp19_3_9=badge-avatar-card&frame_names=polish&mvp19_3_13=badge-frame-final-polish&mvp19_3_14=final-spacing-parity&mvp19_3_15=profile-backgrounds&mvp19_3_16=profile-backgrounds-ux-corrective&mvp19_3_18=background-final-card-grid&mvp19_3_19=selected-green-frame-align&mvp19_3_20=avatar-store-action&mvp19_3_24=profile-card-parity&mvp19_3_25=profile-background-full-surface&mvp19_3_26=profile-card-copy-premium-bg&mvp19_3_27=profile-density-abyss-frame-polish',
        'consistency_css' => './assets/css/production-v99-profile-reaction-polish.css?v=2&mvp19_3=cumulative-reaction-cards&layout=bounded-packs&owned=passive-status&profile_nav=direct-sync-v2&row_footer=stretch-v1&pack4=single-row-v1&profile_first=structural-route-guard-v1&shell_mobile=atomic-v1&profile_hidden=zero-v1&shell_motion=atomic-restored-v2&profile_motion=atomic-none-v1',
        'consistency_css_base' => './assets/css/production-v97-reactions.css?v=2&mvp19_3=ingame-corrective',
        'bootstrap' => './assets/js/app-bootstrap-v2.js?v=2&mvp16=version-manifest',
    ],
    'localization' => ['version'=>'keys-v1','default_locale'=>'ru','manifest'=>'./locales/manifest.json'],
];